import streamlit as st
import pandas as pd
import numpy as np
import requests
import json
import time
from tabfm import TabFMClassifier
from tabfm import tabfm_v1_0_0_pytorch as tabfm_v1_0_0

# Model Configuration
OLLAMA_MODEL = "qwen3:4b"
OLLAMA_URL = "http://localhost:11434/api/generate"

st.set_page_config(page_title="TabFM Zero-Shot Analyzer", layout="wide", page_icon="📊")

st.title("📊 TabFM Zero-Shot Analyzer")
st.markdown("Instantly predict tabular outcomes using **TabFM** (zero-shot) and generate insights using a local **Ollama** LLM without reasoning overhead.")

@st.cache_resource
def load_tabfm():
    return tabfm_v1_0_0.load()

# Load TabFM Model
try:
    with st.spinner("Loading TabFM (PyTorch Backend)..."):
        model = load_tabfm()
        clf = TabFMClassifier(model=model)
except Exception as e:
    st.error(f"Failed to load TabFM. Did you install it properly? Error: {e}")
    st.stop()

# Layout
col1, col2 = st.columns(2)

with col1:
    st.subheader("1. Input Data (Training Context)")
    X_train = pd.DataFrame({
        "age": [25.0, 45.0, 35.0, 50.0],
        "job": ["engineer", "manager", "engineer", "manager"],
        "income": [80000, 120000, 90000, 130000]
    })
    y_train = np.array(["low_risk", "high_risk", "low_risk", "high_risk"])
    st.dataframe(X_train.assign(Risk=y_train), use_container_width=True)

with col2:
    st.subheader("2. Target Data (To Predict)")
    X_test = pd.DataFrame({
        "age": [30.0, 48.0],
        "job": ["engineer", "manager"],
        "income": [85000, 125000]
    })
    st.dataframe(X_test, use_container_width=True)

if st.button("Run Prediction & Analyze", type="primary"):
    # Step 1: TabFM Prediction
    with st.spinner("Running TabFM zero-shot classification..."):
        clf.fit(X_train, y_train)
        predictions = clf.predict(X_test)
        probabilities = clf.predict_proba(X_test)
        
    st.subheader("3. TabFM Predictions")
    results_df = X_test.copy()
    results_df["Predicted_Risk"] = predictions
    results_df["Confidence"] = np.max(probabilities, axis=1)
    
    st.dataframe(results_df.style.highlight_max(subset=['Confidence'], color='lightgreen'), use_container_width=True)

    # Step 2: Ollama LLM Insights
    st.subheader("4. AI Insights (Ollama)")
    prompt = (
        "Analyze these risk prediction results:\n"
        f"{results_df.to_string()}\n"
        "Give a short, crisp 2-sentence summary of the risk profile."
    )
    
    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.0
        }
    }
    
    with st.spinner(f"Generating insights using {OLLAMA_MODEL}..."):
        try:
            start_time = time.time()
            response = requests.post(OLLAMA_URL, json=payload, timeout=30)
            if response.status_code == 200:
                result = response.json().get("response", "").strip()
                st.success(result)
                st.caption(f"Insight generated by {OLLAMA_MODEL} in {time.time() - start_time:.2f}s")
                
                output_content = (
                    "## 1. Input Data (Training Context)\n"
                    f"```text\n{X_train.assign(Risk=y_train).to_string()}\n```\n\n"
                    "## 2. Target Data (To Predict)\n"
                    f"```text\n{X_test.to_string()}\n```\n\n"
                    "## 3. TabFM Predictions\n"
                    f"```text\n{results_df.to_string()}\n```\n\n"
                    "## 4. AI Insights\n"
                    f"{result}\n"
                )
                with open("outputs.md", "w", encoding="utf-8") as f:
                    f.write(output_content)
            else:
                st.error(f"Failed to connect to Ollama. HTTP {response.status_code}")
        except Exception as e:
            st.error(f"Error calling Ollama: {e}. Please ensure Ollama is running.")
